#!/bin/sh


# certbot certonly --apache --domains intern.skgb.de,intern2.skgb.de,clyde.skgb.de --email webmaster+le@skgb.de --agree-tos --non-interactive
# --test-cert / --dry-run

if ! /usr/bin/certbot renew > /var/log/letsencrypt/renew.log 2>&1
then
    echo Automated renewal failed:
    cat /var/log/letsencrypt/renew.log
    exit 1
fi

exit 0



# https://letsencrypt.org/getting-started/
# https://github.com/letsencrypt/letsencrypt
# https://github.com/diafygi/acme-tiny
# https://letsencrypt.readthedocs.org/en/latest/using.html
# https://httpd.apache.org/docs/2.4/mod/mod_ssl.html
# https://www.ssllabs.com/ssltest/analyze.html?d=intern2.skgb.de
